const data ={
  "bomboloExecutive": [
    { "id": 1, "name": { "first": "Alice", "last": "Nováková" }, "salary": { "fix": 45000, "bonus": 5000 }, "status": "ACTIVE" },
    { "id": 2, "name": { "first": "Petr", "last": "Svoboda" }, "salary": { "fix": 40000, "bonus": 0 }, "status": "INACTIVE" },
    { "id": 3, "name": { "first": "Eva", "last": "Dlouhá" }, "salary": { "fix": 55000, "bonus": 10000 }, "status": "ACTIVE" },
    { "id": 4, "name": { "first": "Karel", "last": "Malý" }, "salary": { "fix": 38000, "bonus": 2000 }, "status": "ACTIVE" },
    { "id": 5, "name": { "first": "Jana", "last": "Rychlá" }, "salary": { "fix": 62000, "bonus": 15000 }, "status": "ACTIVE" },
    { "id": 6, "name": { "first": "Tomáš", "last": "Veselý" }, "salary": { "fix": 48000, "bonus": 0 }, "status": "INACTIVE" },
    { "id": 7, "name": { "first": "Lukáš", "last": "Horák" }, "salary": { "fix": 51000, "bonus": 5000 }, "status": "ACTIVE" },
    { "id": 8, "name": { "first": "Monika", "last": "Bílá" }, "salary": { "fix": 43000, "bonus": 3000 }, "status": "ACTIVE" },
    { "id": 9, "name": { "first": "David", "last": "Černý" }, "salary": { "fix": 90000, "bonus": 20000 }, "status": "ACTIVE" },
    { "id": 10, "name": { "first": "Petra", "last": "Němcová" }, "salary": { "fix": 35000, "bonus": 1000 }, "status": "INACTIVE" },
    { "id": 11, "name": { "first": "Michal", "last": "Dvořák" }, "salary": { "fix": 58000, "bonus": 8000 }, "status": "ACTIVE" },
    { "id": 12, "name": { "first": "Lenka", "last": "Králová" }, "salary": { "fix": 46000, "bonus": 4000 }, "status": "ACTIVE" },
    { "id": 13, "name": { "first": "Ondřej", "last": "Pospíšil" }, "salary": { "fix": 53000, "bonus": 0 }, "status": "ACTIVE" },
    { "id": 14, "name": { "first": "Zuzana", "last": "Vlčková" }, "salary": { "fix": 70000, "bonus": 10000 }, "status": "ACTIVE" },
    { "id": 15, "name": { "first": "Marek", "last": "Fišer" }, "salary": { "fix": 41000, "bonus": 2500 }, "status": "INACTIVE" },
    { "id": 16, "name": { "first": "Barbora", "last": "Jelínková" }, "salary": { "fix": 49000, "bonus": 6000 }, "status": "ACTIVE" },
    { "id": 17, "name": { "first": "Jakub", "last": "Blažek" }, "salary": { "fix": 60000, "bonus": 0 }, "status": "ACTIVE" },
    { "id": 18, "name": { "first": "Adam", "last": "Kříž" }, "salary": { "fix": 44000, "bonus": 4000 }, "status": "ACTIVE" },
    { "id": 19, "name": { "first": "Veronika", "last": "Kopecká" }, "salary": { "fix": 52000, "bonus": 7000 }, "status": "ACTIVE" },
    { "id": 20, "name": { "first": "Filip", "last": "Beneš" }, "salary": { "fix": 39000, "bonus": 1500 }, "status": "INACTIVE" },
    { "id": 21, "name": { "first": "Tereza", "last": "Doležalová" }, "salary": { "fix": 65000, "bonus": 12000 }, "status": "ACTIVE" },
    { "id": 22, "name": { "first": "Martin", "last": "Šimek" }, "salary": { "fix": 56000, "bonus": 5000 }, "status": "ACTIVE" },
    { "id": 23, "name": { "first": "Lucie", "last": "Mašková" }, "salary": { "fix": 47500, "bonus": 2500 }, "status": "ACTIVE" },
    { "id": 24, "name": { "first": "Vojtěch", "last": "Urban" }, "salary": { "fix": 80000, "bonus": 15000 }, "status": "ACTIVE" },
    { "id": 25, "name": { "first": "Klára", "last": "Říhová" }, "salary": { "fix": 42000, "bonus": 0 }, "status": "INACTIVE" }
  ],
  "norwayLegion": [
    { "jmeno": "Jan Kovář", "plat": "42 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Lucie Veselá", "plat": "38 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Brno" } },
    { "jmeno": "Martin Černý", "plat": "55 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Ostrava" } },
    { "jmeno": "Anna Procházková", "plat": "35 500 Kč", "detaily": { "uvazek": "DPP", "mesto": "Plzeň" } },
    { "jmeno": "Jiří Novotný", "plat": "60 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Hana Sýkorová", "plat": "48 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Liberec" } },
    { "jmeno": "Pavel Kučera", "plat": "40 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Brno" } },
    { "jmeno": "Simona Valentová", "plat": "32 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Olomouc" } },
    { "jmeno": "Robert Vacek", "plat": "75 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Dana Poláková", "plat": "41 500 Kč", "detaily": { "uvazek": "HPP", "mesto": "Pardubice" } },
    { "jmeno": "Radek Tichý", "plat": "39 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Zlín" } },
    { "jmeno": "Ivana Machová", "plat": "52 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Brno" } },
    { "jmeno": "Stanislav Holub", "plat": "46 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Hradec Králové" } },
    { "jmeno": "Nikola Ševčíková", "plat": "36 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Praha" } },
    { "jmeno": "Viktor Kolář", "plat": "58 500 Kč", "detaily": { "uvazek": "HPP", "mesto": "Ostrava" } },
    { "jmeno": "Romana Krejčí", "plat": "43 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "České Budějovice" } },
    { "jmeno": "Milan Řezník", "plat": "90 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Alena Mrázová", "plat": "34 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Ústí nad Labem" } },
    { "jmeno": "Jaroslav Bednář", "plat": "49 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Brno" } },
    { "jmeno": "Eliška Tomanová", "plat": "44 500 Kč", "detaily": { "uvazek": "HPP", "mesto": "Jihlava" } },
    { "jmeno": "Daniel Vávra", "plat": "53 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Kristýna Soukupová", "plat": "37 000 Kč", "detaily": { "uvazek": "DPP", "mesto": "Kladno" } },
    { "jmeno": "Vladimír Janeček", "plat": "65 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Praha" } },
    { "jmeno": "Martina Dušková", "plat": "40 500 Kč", "detaily": { "uvazek": "HPP", "mesto": "Karviná" } },
    { "jmeno": "Patrik Urbanec", "plat": "47 000 Kč", "detaily": { "uvazek": "HPP", "mesto": "Most" } }
  ],
  "apolloDiscounted": [
    { "id": 201, "profile": { "username": "tom_smith", "personal_data": { "full_name": "Thomas Smith" } }, "finance": { "amount": 3500, "currency": "USD" } },
    { "id": 202, "profile": { "username": "hans_m", "personal_data": { "full_name": "Hans Muller" } }, "finance": { "amount": 4800, "currency": "EUR" } },
    { "id": 203, "profile": { "username": "sarah_j", "personal_data": { "full_name": "Sarah Jones" } }, "finance": { "amount": 120000, "currency": "CZK" } },
    { "id": 204, "profile": { "username": "jean_p", "personal_data": { "full_name": "Jean Pierre" } }, "finance": { "amount": 3200, "currency": "EUR" } },
    { "id": 205, "profile": { "username": "mike_d", "personal_data": { "full_name": "Michael Davis" } }, "finance": { "amount": 4500, "currency": "USD" } },
    { "id": 206, "profile": { "username": "anna_k", "personal_data": { "full_name": "Anna Kowalska" } }, "finance": { "amount": 85000, "currency": "CZK" } },
    { "id": 207, "profile": { "username": "marco_r", "personal_data": { "full_name": "Marco Rossi" } }, "finance": { "amount": 2900, "currency": "EUR" } },
    { "id": 208, "profile": { "username": "emily_w", "personal_data": { "full_name": "Emily Wilson" } }, "finance": { "amount": 5200, "currency": "USD" } },
    { "id": 209, "profile": { "username": "lucas_s", "personal_data": { "full_name": "Lucas Silva" } }, "finance": { "amount": 4100, "currency": "EUR" } },
    { "id": 210, "profile": { "username": "david_b", "personal_data": { "full_name": "David Brown" } }, "finance": { "amount": 3800, "currency": "USD" } },
    { "id": 211, "profile": { "username": "sophie_l", "personal_data": { "full_name": "Sophie Laurent" } }, "finance": { "amount": 5500, "currency": "EUR" } },
    { "id": 212, "profile": { "username": "oliver_t", "personal_data": { "full_name": "Oliver Taylor" } }, "finance": { "amount": 95000, "currency": "CZK" } },
    { "id": 213, "profile": { "username": "maria_g", "personal_data": { "full_name": "Maria Garcia" } }, "finance": { "amount": 2700, "currency": "EUR" } },
    { "id": 214, "profile": { "username": "james_h", "personal_data": { "full_name": "James Harris" } }, "finance": { "amount": 6000, "currency": "USD" } },
    { "id": 215, "profile": { "username": "elena_p", "personal_data": { "full_name": "Elena Petrova" } }, "finance": { "amount": 110000, "currency": "CZK" } },
    { "id": 216, "profile": { "username": "franz_w", "personal_data": { "full_name": "Franz Weber" } }, "finance": { "amount": 4200, "currency": "EUR" } },
    { "id": 217, "profile": { "username": "linda_c", "personal_data": { "full_name": "Linda Clark" } }, "finance": { "amount": 3100, "currency": "USD" } },
    { "id": 218, "profile": { "username": "johan_a", "personal_data": { "full_name": "Johan Andersson" } }, "finance": { "amount": 5800, "currency": "EUR" } },
    { "id": 219, "profile": { "username": "robert_m", "personal_data": { "full_name": "Robert Miller" } }, "finance": { "amount": 4900, "currency": "USD" } },
    { "id": 220, "profile": { "username": "julia_s", "personal_data": { "full_name": "Julia Schmidt" } }, "finance": { "amount": 3600, "currency": "EUR" } },
    { "id": 221, "profile": { "username": "william_j", "personal_data": { "full_name": "William Johnson" } }, "finance": { "amount": 75000, "currency": "CZK" } },
    { "id": 222, "profile": { "username": "alessandro_b", "personal_data": { "full_name": "Alessandro Bianchi" } }, "finance": { "amount": 3300, "currency": "EUR" } },
    { "id": 223, "profile": { "username": "chloe_e", "personal_data": { "full_name": "Chloe Evans" } }, "finance": { "amount": 4000, "currency": "USD" } },
    { "id": 224, "profile": { "username": "lars_n", "personal_data": { "full_name": "Lars Nielsen" } }, "finance": { "amount": 5100, "currency": "EUR" } },
    { "id": 225, "profile": { "username": "katarina_k", "personal_data": { "full_name": "Katarina Kovac" } }, "finance": { "amount": 92000, "currency": "CZK" } }
  ]
}
